### ISSUE TITLE
Lag after pressing enter on empty row is too long

### ISSUE THREAD

**Issue by cool-RR** [click-contrib/click-repl#10]
I launch the repl and press enter without typing anything, and I have to wait about 0.5 seconds before the next prompt appears. I tried this several times and I get the delay every time. I guess some kind of heavy thinking is performed? Maybe put in a check that if the string is empty, just show another prompt without thinking too much?

**Comment by untitaker** [comment]
The heavy thinking is just for showing the prompt, not for processing the input. I'm not sure how to improve that situation, I guess it arises from me using the `prompt` shortcut instead of a "permanent object". If you find anything in the docs of prompt-toolkit, please let me know.

**Comment by jonathanslenders** [comment]
What version of prompt_toolkit are you using? Can you try to upgrade to the latest version and see whether it still happens? There were some improvements done in one of the latest versions.

In any case, it is encouraged to keep using the ``prompt`` shortcut. This API is guaranteed to be the most stable. If there is some delay, that is a bug.

**Comment by untitaker** [comment]
Oh, the latest version is indeed quite fast!

**Comment by cool-RR** [comment]
I upgraded now from `prompt_toolkit` 1.0.3 to 1.0.6 and now the lag is gone! Thank you!
