### ISSUE TITLE
Start showing command options before typed

### ISSUE THREAD

**Issue by cool-RR** [click-contrib/click-repl#11]
My motivation for using click-repl is to make my script more discovereable for users. So it'll be nice if, when they're starting to type a command, the options for that command would show on the screen so they could choose from them, even without typing `-`.

**Comment by untitaker** [comment]
You can do this yourself already by writing your own repl command from which you print the message and invoke the repl function. This is not documented, so leaving this open as docs issue.

On 30 July 2016 22:31:55 CEST, Ram Rachum <notifications@github.com> wrote:
>My motivation for using click-repl is to make my script more
>discovereable for users. So it'll be nice if, when they're starting to
>type a command, the options for that command would show on the screen
>so they could choose from them, even without typing `-`.
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/click-contrib/click-repl/issues/11

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by untitaker** [comment]
That is just the standard behavior of python-prompt-toolkit. I don't know how to change it.

**Comment by BobWhitelock** [comment]
`click-repl` appears to work like this for me when using `master`, after I added [this commit](https://github.com/click-contrib/click-repl/commit/5f92968e468c4e17313438df38a48a5666a5be23). Options for a command are now shown as soon as a command and a space following it are entered - this sounds like what the original issue is asking for unless I'm mistaken.

**Comment by lwm** [comment]
>  this sounds like what the original issue is asking for unless I'm mistaken.

Yep, looks like you can close this one off. The completion is pretty cool so far.
