### ISSUE TITLE
Put click-repl on PyPI

### ISSUE THREAD

**Issue by cool-RR** [click-contrib/click-repl#12]
I understand that click-repl is still new and unstable, but I think it's okay to put it on PyPI and mark it as alpha. It'll make it easier for me to reference to specific versions of it as dependencies.

**Comment by cool-RR** [comment]
![dd43d5de3300783b5ee2e205d53abdd9](https://cloud.githubusercontent.com/assets/56778/18610289/d177e3ca-7d20-11e6-9f51-5dd68b791d64.jpg)

**Comment by untitaker** [comment]
It's on PyPI now. Regarding the other issues you opened: Patches welcome. :P

**Comment by cool-RR** [comment]
Thank you!!! 
![bird turning head](https://cloud.githubusercontent.com/assets/56778/18614015/7f61d5d2-7d8e-11e6-9927-e03697c63232.gif)
