### ISSUE TITLE
tab display nested commands

### ISSUE THREAD

**Issue by rbonthond** [click-contrib/click-repl#13]
it looks like tab will show a list for commands, but this doesn't seem to work for the subcommands

**Comment by untitaker** [comment]
Could you give an example? Thanks!

**Comment by untitaker** [comment]
@rbonthond Could you give an example?

**Comment by rbonthond** [comment]
hi, I created a tool that has several layers of nested subcommands, but with the repl the tab will only expands the 1st level of subcommands, not the ones under it.
