### ISSUE TITLE
setup install is suppose to create an egg or a normal folder?

### ISSUE THREAD

**Issue by pamag** [click-contrib/click-repl#17]
I have cloned from github and done python setup.py install in a virtualenv en macOSX and I have a "click_repl-0.1.0-py3.5.egg" instead click_repl/ in my "site-packages". Is that the intended behaviour?

**Comment by untitaker** [comment]
No, but it's also not something I control. Check if the output contains any error messages, the installation probably failed.

**Comment by pamag** [comment]
It installed eggs for click-repl and also the dependencies where eggs. I uninstalled all of them and installed successfully from pip.
