### ISSUE TITLE
Flag Autocompletion Not Working Past First Flag

### ISSUE THREAD

**Issue by Lidaja** [click-contrib/click-repl#19]
If I have multiple possible flags for the click command, it will give me the autocomplete options for the first flag entered after the command name, but every next flag will not have any kind of autocompletion,

**Comment by untitaker** [comment]
Might be fixed in master.

**Comment by BobWhitelock** [comment]
I can confirm this does appear to work for me on master.

**Comment by Lidaja** [comment]
Bug is fixed in master, thank you!
