### ISSUE TITLE
0.1.3 release?

### ISSUE THREAD

**Issue by iorbitearth** [click-contrib/click-repl#38]
Is there any interest in creating a new release and making it available on pypi? Some features and bug fixes in master (history, etc) would be nice to utilize.

Some open pull requests look handy as well, e.g. (#33) :smiley:

**Comment by untitaker** [comment]
Done, thanks for the reminder :)

**Comment by untitaker** [comment]
(I couldn't add #33 because of missing changes. If it lands I'd rather do a 0.x release though)
