### ISSUE TITLE
Release providing argument choices

### ISSUE THREAD

**Issue by iorbitearth** [click-contrib/click-repl#42]
Latest release was in January and I believe was generated just before a branch was merged that supports autocompletion of argument choices (#33).  I verified this with my application using v0.1.3 vs top of tree master.

It would be great to get a new official release out on pypi that includes this feature. Once 0.1.4 (or whatever) is released, I would port my app from 0.1.2 and release to my set of users.

Thanks for all the effort!

**Comment by untitaker** [comment]
done
