### ISSUE TITLE
repl is not maintained after first command

### ISSUE THREAD

**Issue by brad-alexander** [click-contrib/click-repl#47]
I tried the example in windows10 / python3.7 and the repl exits after the first command unlike the example where you press ctrl+c to exit. Wondering if this is expected due to platform differences, and/or maybe its a quick fix using the advanced method.

    C:\Users\.....> my-app.py repl
    > hello
    Hello!

    C:\Users\.....>

**Comment by euri10** [comment]
it's not windows, I got the same on linux, I tracked the issue to be the 7.0 release of click and the standalone_mode flag that messes things up, pinning click to 6.7 fixes the issue in the meantime, before further investigation.

**Comment by brad-alexander** [comment]
the pinning worked for me.  thanks for the reply. 💯

I've adjusted the title to better reflect the problem (removed windows reference). I'm fine closing the issue but I'll defer to any external guidance since it might prevent duplicates from being raised.

**Comment by WhyNotHugo** [comment]
I'd rather we keep this open until we actually fix this, since pinning an older click is just a workaround that won't last.

**Comment by theazureshadow** [comment]
I think this duplicates #50, which is fixed by #51.

**Comment by theazureshadow** [comment]
@brad-alexander, @euri10: Can you try with `0.1.6`?

**Comment by euri10** [comment]
tested on my project and it works perfect :) thanks
