### ISSUE TITLE
click v7 breaks click_repl

### ISSUE THREAD

**Issue by mgdelmonte** [click-contrib/click-repl#50]
`click_repl` works with `click==6.7` but upgrading to `click==7.0` breaks it.  Sample code:

```
from __future__ import print_function
import click
import click_repl

@click.group()
def cli():
    print("in cli")

@cli.command()
def test():
    print("in test")

@cli.command()
def repl():
    click_repl.repl(click.get_current_context())

if __name__ == '__main__':
    cli()
```

Running with click v6.7, the repl works.  With click 7.0, the repl exits after the first command.

**Comment by theazureshadow** [comment]
We hit this issue as well.

**Comment by theazureshadow** [comment]
Pretty sure it has to do with this PR: https://github.com/pallets/click/pull/1098

**Comment by theazureshadow** [comment]
Please take a look at my PR #51, which should fix this in a backwards-compatible manner.

**Comment by theazureshadow** [comment]
@mgdelmonte: Can you try with `0.1.6`?

**Comment by mgdelmonte** [comment]
works great -- thanks!
