### ISSUE TITLE
Don't suggest hidden commands&options

### ISSUE THREAD

**Issue by littlemo** [click-contrib/click-repl#64]
commands&options which has hidden should not be shown in the completion list.

**Comment by jannismain** [comment]
I also stumbled upon this and support the PR #65 :-)

**Comment by auvipy** [comment]
> I also stumbled upon this and support the PR #65 :-)

can you write some test for that PR

**Comment by GhostOps77** [comment]
Solved in #86 

@auvipy you can close this issue
