### ISSUE TITLE
No completion of type=click.Choice for Options

### ISSUE THREAD

**Issue by mirhmousavi** [click-contrib/click-repl#66]
Hi
thanks for this great library.
I'm wondering that does completion for `type=click.Choice` for options available?
this is my code

```python
import click
from click_repl import repl


@click.group(invoke_without_command=True,)
@click.pass_context
def main(ctx):
    if not ctx.invoked_subcommand:
        repl(click.get_current_context())

@main.group()
def user():
    pass

@user.command()
@click.option('-type', type=click.Choice(['1', '2']))
def search(name):
    pass

if __name__ == '__main__':
    main()
```

I won't get completion for `-type`

**Comment by untitaker** [comment]
It does not complete any parameter values, but patches welcome!

**Comment by mirhmousavi** [comment]
I'll examine the code to figure out that can I implement it or not
thanks

**Comment by mirhmousavi** [comment]
I made some changes to the library to choice values be shown in prompt
https://github.com/click-contrib/click-repl/pull/67
