### ISSUE TITLE
Allow customizing prompt, e.g. to say "my-app>"

### ISSUE THREAD

**Issue by cool-RR** [click-contrib/click-repl#7]

**Comment by untitaker** [comment]
You can do this yourself already by writing your own repl command from which you print the message and invoke the repl function. This is not documented, so leaving this open as docs issue.

**Comment by untitaker** [comment]
Unsure how to implement.

I'm thinking of making the kwargs for `prompt` here overridable: https://github.com/click-contrib/click-repl/blob/master/click_repl/__init__.py#L128

This means that you'd have to write your own subcommand, with a body like this:

```py

click_repl.repl(ctx, message=u'fooboo> ')
```

**Comment by cool-RR** [comment]
I almost agree. I think that allowing people to specify the arguments to `prompt` is the right way, but please don't do `def repl(old_ctx, **prompt_kwargs):` because then you could never, ever add any more arguments to this function. I would do `def repl(old_ctx, prompt_kwargs=None):` and let them input a dict there.

**Comment by untitaker** [comment]
@cool-RR Okay I made those changes.

**Comment by cool-RR** [comment]
Awesome, thanks!
