### ISSUE TITLE
click-repl and click version 8-a2 (alpha version in master)

### ISSUE THREAD

**Issue by KSchopmeyer** [click-contrib/click-repl#72]
Click version 8.0 is no in early alpha state  and the code for autocompletion has been committed, essentially rewriting the autocomplete functionality.

As part of this work the _bashcomplete function in click.core which is used by click-repl has been completely removed from click which causes a click application that uses click_repl and is testing with the alpha click 8 to fail in startup.

click_repl/__init__.py", line 6, in <module>
    import click._bashcomplete
ModuleNotFoundError: No module named 'click._bashcomplete'

This means to be compatible with click 8.0 click_repl should add code to use the new autocomplete mechanism when use with clic >= 8.0. See the following for more information.

- click issue https://github.com/pallets/click/issues/1484
- click pr https://github.com/pallets/click/pull/1622/files?file-filters%5B%5D=.py&file-filters%5B%5D=.rst
- click preliminary changes  documentation https://click.palletsprojects.com/en/master/changelog/#version-8-0
- click preliminary documentation on the new autocomplete https://click.palletsprojects.com/en/master/shell-completion/

**Comment by thedrow** [comment]
FYI This is preventing us from upgrading Celery to click 8.0.

**Comment by untitaker** [comment]
I need a volunteer to champion this and also take over maintainership (see #73)
