### ISSUE TITLE
click-repl does not work with Click 8.0.0 anymore

### ISSUE THREAD

**Issue by andy-maier** [click-contrib/click-repl#75]
Click 8.0.0 removed an internal name which click-repl depends upon:

E.g. on Python 3.8 on macOS:
```
$ python -c "import click; import click_repl"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/maiera/virtualenvs/pywbemtools38/lib/python3.8/site-packages/click_repl/__init__.py", line 6, in <module>
    import click._bashcomplete
ModuleNotFoundError: No module named 'click._bashcomplete'
```

**Comment by andy-maier** [comment]
In our projects using click-repl, we can mitigate this by pinning click to <8.0.0. At least until the desire to use the new autocompletion of click weighs in ;-)

**Comment by anthraxx** [comment]
@andy-maier that doesnt really work for all t he distro packages. with no click 8 support this will make a major problem for the click-repl distro package

**Comment by jm66** [comment]
Hey @andy-maier take a look at [this branch](https://github.com/jm66/click-repl/tree/click8). I've tested it with Python 3.9.4 on macOS.

**Comment by andy-maier** [comment]
@jm66 I have tried your branch in one of our projects (https://github.com/zhmcclient/zhmccli/pull/173) and it installs fine with click 8.0. I did a few manual tests of using the repl mode of the command and used its auto-completion, and that all worked fine.

So from my perspective, this change is good to go forward.

**Comment by andy-maier** [comment]
@anthraxx I know. I was just trying to make a statement for our projects.

Hopefully the change by @jm66 gets accepted by the new maintainers and a release can be made.

**Comment by thedrow** [comment]
This is blocking Celery from upgrading to Click 8.

**Comment by regisb** [comment]
I think we can close this, now that v0.2.0 is out.

**Comment by untitaker** [comment]
Thank you!
