### ISSUE TITLE
Allow specifying a message to be shown at start of shell session

### ISSUE THREAD

**Issue by cool-RR** [click-contrib/click-repl#8]

**Comment by untitaker** [comment]
You can do this yourself already by writing your own repl command from which you print the message and invoke the repl function. This is not documented, so leaving this open as docs issue.

**Comment by cool-RR** [comment]
How do I write my own `repl` command? Write my own function that calls your `repl` function and adds stuff before it?

**Comment by untitaker** [comment]
Yup

On 31 July 2016 08:27:03 CEST, Ram Rachum <notifications@github.com> wrote:
>How do I write my own `repl` command? Write my own function that calls
>your `repl` function and adds stuff before it? 
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/click-contrib/click-repl/issues/8#issuecomment-236413994

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by untitaker** [comment]
Here's an example:

```py
import click
import click_repl

@click.group()
def cli():
    pass

@cli.command()
@click.pass_context
def repl(ctx):
    click.echo('ayy lmao')
    click_repl.repl(ctx)

cli()
```

**Comment by cool-RR** [comment]
Thanks!

**Comment by untitaker** [comment]
Oops, closed wrong issue.

**Comment by untitaker** [comment]
Meant to close #7

**Comment by lwm** [comment]
I think this is covered by [the advanced usage documentation](https://github.com/click-contrib/click-repl#advanced-usage) and can be closed.
