### ISSUE TITLE
Make a dev branch

### ISSUE THREAD

**Issue by GhostOps77** [click-contrib/click-repl#91]
Things I would like to recommend to this repo
- Create a dev branch from master, so that everyone can add new features and improve code from here, and make updates as version `0.2.1dev0` or something (or make a pypi branch)
- And add an another gh-actions in master that publishes the package to pypi once you've merged the code from dev branch to master branch
- Also, I would also recommend to delete the unnecessary [`ci`](https://github.com/click-contrib/click-repl/tree/ci) branch in this repo

**Comment by GhostOps77** [comment]
I would also suggest you to remove this issue as well as it's already solved
- #56

**Comment by auvipy** [comment]
master branch is generally the dev branch.

**Comment by GhostOps77** [comment]
@auvipy but atleast you make a branch called `pypi` to release the package to pypi automatically using gh-actions
